# Generated by Django 4.0.2 on 2022-02-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='user_rate',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='games.game'),
        ),
    ]
