# Generated by Django 4.0.2 on 2022-03-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_user_rate_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[(0, 'Cтратегия'), (1, 'На двоих'), (2, 'Экономическая'), (3, 'Кооперативная'), (4, 'Вечеринка')], default='Стратегия', max_length=255),
        ),
    ]
